// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: mandatory4/grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartAgrawalaService_Access_FullMethodName       = "/RicartAgrawalaService/Access"
	RicartAgrawalaService_Confirmation_FullMethodName = "/RicartAgrawalaService/Confirmation"
)

// RicartAgrawalaServiceClient is the client API for RicartAgrawalaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartAgrawalaServiceClient interface {
	Access(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AccessRequest, AccessRequest], error)
	Confirmation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Reply, Reply], error)
}

type ricartAgrawalaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartAgrawalaServiceClient(cc grpc.ClientConnInterface) RicartAgrawalaServiceClient {
	return &ricartAgrawalaServiceClient{cc}
}

func (c *ricartAgrawalaServiceClient) Access(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AccessRequest, AccessRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RicartAgrawalaService_ServiceDesc.Streams[0], RicartAgrawalaService_Access_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AccessRequest, AccessRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RicartAgrawalaService_AccessClient = grpc.BidiStreamingClient[AccessRequest, AccessRequest]

func (c *ricartAgrawalaServiceClient) Confirmation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Reply, Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RicartAgrawalaService_ServiceDesc.Streams[1], RicartAgrawalaService_Confirmation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Reply, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RicartAgrawalaService_ConfirmationClient = grpc.BidiStreamingClient[Reply, Reply]

// RicartAgrawalaServiceServer is the server API for RicartAgrawalaService service.
// All implementations must embed UnimplementedRicartAgrawalaServiceServer
// for forward compatibility.
type RicartAgrawalaServiceServer interface {
	Access(grpc.BidiStreamingServer[AccessRequest, AccessRequest]) error
	Confirmation(grpc.BidiStreamingServer[Reply, Reply]) error
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

// UnimplementedRicartAgrawalaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartAgrawalaServiceServer struct{}

func (UnimplementedRicartAgrawalaServiceServer) Access(grpc.BidiStreamingServer[AccessRequest, AccessRequest]) error {
	return status.Errorf(codes.Unimplemented, "method Access not implemented")
}
func (UnimplementedRicartAgrawalaServiceServer) Confirmation(grpc.BidiStreamingServer[Reply, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method Confirmation not implemented")
}
func (UnimplementedRicartAgrawalaServiceServer) mustEmbedUnimplementedRicartAgrawalaServiceServer() {}
func (UnimplementedRicartAgrawalaServiceServer) testEmbeddedByValue()                               {}

// UnsafeRicartAgrawalaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartAgrawalaServiceServer will
// result in compilation errors.
type UnsafeRicartAgrawalaServiceServer interface {
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

func RegisterRicartAgrawalaServiceServer(s grpc.ServiceRegistrar, srv RicartAgrawalaServiceServer) {
	// If the following call pancis, it indicates UnimplementedRicartAgrawalaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartAgrawalaService_ServiceDesc, srv)
}

func _RicartAgrawalaService_Access_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RicartAgrawalaServiceServer).Access(&grpc.GenericServerStream[AccessRequest, AccessRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RicartAgrawalaService_AccessServer = grpc.BidiStreamingServer[AccessRequest, AccessRequest]

func _RicartAgrawalaService_Confirmation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RicartAgrawalaServiceServer).Confirmation(&grpc.GenericServerStream[Reply, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RicartAgrawalaService_ConfirmationServer = grpc.BidiStreamingServer[Reply, Reply]

// RicartAgrawalaService_ServiceDesc is the grpc.ServiceDesc for RicartAgrawalaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartAgrawalaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RicartAgrawalaService",
	HandlerType: (*RicartAgrawalaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Access",
			Handler:       _RicartAgrawalaService_Access_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Confirmation",
			Handler:       _RicartAgrawalaService_Confirmation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mandatory4/grpc/proto.proto",
}
