// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartAgrawalaService_RequestAndReply_FullMethodName = "/RicartAgrawalaService/RequestAndReply"
)

// RicartAgrawalaServiceClient is the client API for RicartAgrawalaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartAgrawalaServiceClient interface {
	RequestAndReply(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type ricartAgrawalaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartAgrawalaServiceClient(cc grpc.ClientConnInterface) RicartAgrawalaServiceClient {
	return &ricartAgrawalaServiceClient{cc}
}

func (c *ricartAgrawalaServiceClient) RequestAndReply(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, RicartAgrawalaService_RequestAndReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartAgrawalaServiceServer is the server API for RicartAgrawalaService service.
// All implementations must embed UnimplementedRicartAgrawalaServiceServer
// for forward compatibility.
type RicartAgrawalaServiceServer interface {
	RequestAndReply(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

// UnimplementedRicartAgrawalaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartAgrawalaServiceServer struct{}

func (UnimplementedRicartAgrawalaServiceServer) RequestAndReply(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAndReply not implemented")
}
func (UnimplementedRicartAgrawalaServiceServer) mustEmbedUnimplementedRicartAgrawalaServiceServer() {}
func (UnimplementedRicartAgrawalaServiceServer) testEmbeddedByValue()                               {}

// UnsafeRicartAgrawalaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartAgrawalaServiceServer will
// result in compilation errors.
type UnsafeRicartAgrawalaServiceServer interface {
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

func RegisterRicartAgrawalaServiceServer(s grpc.ServiceRegistrar, srv RicartAgrawalaServiceServer) {
	// If the following call pancis, it indicates UnimplementedRicartAgrawalaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartAgrawalaService_ServiceDesc, srv)
}

func _RicartAgrawalaService_RequestAndReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartAgrawalaServiceServer).RequestAndReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartAgrawalaService_RequestAndReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartAgrawalaServiceServer).RequestAndReply(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartAgrawalaService_ServiceDesc is the grpc.ServiceDesc for RicartAgrawalaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartAgrawalaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RicartAgrawalaService",
	HandlerType: (*RicartAgrawalaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestAndReply",
			Handler:    _RicartAgrawalaService_RequestAndReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
